# Set the base image (for a simple deploy use the python image with your needed version)
# Use command FROM
FROM python:3.9.13

# Copy all files that you need for your workdir (your name choice)
# Use command COPY

# Set your workdir (move "yourself" to your workdir to run commands inside there)
# Use command WORKDIR

# Install your app requirements and run necessary commands
# Use command RUN

# Expose a port to your container listen
# Use command EXPOSE

# Define the command to execute your container
# Use command CMD (only one per dockerfile)
